FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/* && rm -rf /etc/nginx/conf.d/default.conf && rm -rf /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx
COPY build/ /usr/share/nginx/html

#Optional to mention expose as it will be taken by nginx sever , port 80 wil be taken from nginx server
EXPOSE 80
