version: '3'
services:
  api:
    build: ./backend
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/app:ro
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Ethx1997!
      - POSTGRES_DB=dwapp_db
    volumes:
      - postgres-db:/var/lib/postgresql/data
  frontend:
    stdin_open: true
    build: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    depends_on:
      - api
volumes:
  postgres-db: