version: '3'
services:
  api:
    build: ./backend
    command: bash -c "alembic upgrade head && gunicorn --bind 0.0.0.0:8000 "main:app" -k uvicorn.workers.UvicornWorker"
    volumes:
      - ./backend:/app:ro
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
  postgres:
    image: postgres
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
#   frontend:
#     stdin_open: true
#     build: ./frontend
#     command: bash -c "npm run start"
#     volumes:
#       - /app/node_modules
#       - ./frontend:/app:ro
#     ports:
#       - "3000:3000"
#     env_file:
#       - ./frontend/.env
#     depends_on:
#       - api
volumes:
  postgres-db: