"""init_tables

Revision ID: e69308da4765
Revises: 291b6a64d988
Create Date: 2022-12-04 18:51:38.360956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e69308da4765'
down_revision = '291b6a64d988'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
