"""init_tables

Revision ID: fc62e717d359
Revises: 
Create Date: 2023-02-10 23:47:00.760073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc62e717d359'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('university',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo_file_name', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('uni_type', sa.String(), nullable=False),
    sa.Column('religious_affiliation', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('tuition_in_state', sa.String(), nullable=False),
    sa.Column('tuition_out_state', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('num_ugrad_students', sa.String(), nullable=False),
    sa.Column('four_years', sa.String(), nullable=False),
    sa.Column('six_years', sa.String(), nullable=False),
    sa.Column('black_aa', sa.Float(), nullable=False),
    sa.Column('latinx', sa.Float(), nullable=False),
    sa.Column('aapi', sa.Float(), nullable=False),
    sa.Column('white', sa.Float(), nullable=False),
    sa.Column('mixed_race', sa.Float(), nullable=False),
    sa.Column('unknown', sa.Float(), nullable=False),
    sa.Column('international', sa.Float(), nullable=False),
    sa.Column('ethnicity', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('admission_rate', sa.String(), nullable=False),
    sa.Column('selectivity', sa.String(), nullable=False),
    sa.Column('gpa_hs', sa.String(), nullable=True),
    sa.Column('act', sa.String(), nullable=True),
    sa.Column('sat_rw_score', sa.String(), nullable=False),
    sa.Column('sat_math', sa.String(), nullable=False),
    sa.Column('common_app', sa.String(), nullable=False),
    sa.Column('tests', sa.String(), nullable=False),
    sa.Column('essay', sa.String(), nullable=False),
    sa.Column('recommendations', sa.String(), nullable=False),
    sa.Column('interview', sa.String(), nullable=False),
    sa.Column('other', sa.String(), nullable=False),
    sa.Column('other_notes', sa.String(), nullable=True),
    sa.Column('on_campus_housing_availability', sa.String(), nullable=False),
    sa.Column('living_learning_communities', sa.String(), nullable=False),
    sa.Column('on_campus_housing_requirement', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_university_id'), 'university', ['id'], unique=False)
    op.create_table('users',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.String(), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('survey',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('university_type', sa.String(), nullable=False),
    sa.Column('geo_setting', sa.String(), nullable=False),
    sa.Column('school_size', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('selectivity', sa.String(), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_id'), 'survey', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_id'), table_name='survey')
    op.drop_table('survey')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_university_id'), table_name='university')
    op.drop_table('university')
    # ### end Alembic commands ###
