apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwebapp-api
  labels:
    name: dwebapp-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dwebapp-api
  template:
    metadata:
      labels:
        app: dwebapp-api
    spec:
      containers:
        - name: dwebapp-api
          image: aikyab4u/dwebapp-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: env-file
              readOnly: true
              mountPath: "/app/.env"
              subPath: .env
          resources:
            limits:
              memory: 100Mi
              cpu: 50m
            requests:
              memory: 40Mi
              cpu: 20m
      volumes:
        - name: env-file
          secret:
            secretName: dwebapp-api-credentials